### PR TITLE
Kegman 0.7.1 ui fix

### PR DESCRIPTION
**Pull request by eFiniLan**
Fix ui black screen issue.

Instead of getting temp from thermald, we just read the value from system (same as what they do anyway.)

it will read temp value every 5 seconds once vision is started.

### CODE REVIEW

**Comment by kegman** [comment]
Hey man thanks for the PR.  I tried merging but tmux session gives me a red UI process......  any ideas?

**Comment by kegman** [comment]
compile manually didn't give me any errors btw

**Comment by eFiniLan** [comment]
ahh... do you still have the issue? I just tried and it worked fine?

**Comment by kegman** [comment]
Tried applying again (to temp12 branch) and temp works, disk space is showing 0 though..  I'll have to take a closer look

**Pull request merged**
