### PR TITLE
Clean up and update Live Tuner

### PR DESCRIPTION
**Pull request by kishkaru**
Cleaned up and updated Live Tuner. Tested working fine on GM, but please test on Honda to make sure everything works fine.

### CODE REVIEW

**Comment by kegman** [comment]
I'll check it out thx kish

**Comment by kegman** [comment]
No worky - won't compile

**Comment by kegman** [comment]
Traceback (most recent call last):
  File "./manager.py", line 506, in <module>
    main()
  File "./manager.py", line 485, in main
    manager_prepare(spinner)
  File "./manager.py", line 417, in manager_prepare
    prepare_managed_process(p)
  File "./manager.py", line 252, in prepare_managed_process
    importlib.import_module(proc)
  File "/data/data/com.termux/files/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data/openpilot/selfdrive/controls/controlsd.py", line 13, in <module>
    from selfdrive.car.car_helpers import get_car, get_startup_alert
  File "/data/openpilot/selfdrive/car/car_helpers.py", line 51, in <module>
    interfaces = load_interfaces(_get_interface_names())
  File "/data/openpilot/selfdrive/car/car_helpers.py", line 23, in load_interfaces
    CarInterface = __import__(path + '.interface', fromlist=['CarInterface']).CarInterface
  File "/data/openpilot/selfdrive/car/chrysler/interface.py", line 4, in <module>
    from selfdrive.controls.lib.drive_helpers import EventTypes as ET, create_event
  File "/data/openpilot/selfdrive/controls/lib/drive_helpers.py", line 4, in <module>
    from selfdrive.kegman_conf import kegman_conf
ImportError: cannot import name 'kegman_conf' from 'selfdrive.kegman_conf' (/data/openpilot/selfdrive/kegman_conf.py)

**Comment by kishkaru** [comment]
I missed converting 1 file during the 0.6.6 -> 0.7 code update. Force-pushed with the latest changes and tested working on GM.

I also reverted lateral Kp/Ki/steerRateCost tuning to stock for Volt as I think they were added by mistake. (they were never used anyway).

**Pull request merged**
