### PR TITLE
Updated README

### PR DESCRIPTION
**Pull request by steveham3**
I wanted to update your README to make it easier to find useful information. I also added some descriptions for all the parameters in kegman.json all in one section. Please review this section to see if any are incorrect. There are still some things I wasn't sure about that I've put ??? next to so if you could confirm and/or answer those that would be great.

You can see what the new README looks like here: https://github.com/steveham3/openpilot

### CODE REVIEW

**Comment by steveham3** [comment]
Thank you for merging.  I'm hoping you can still answer the questions I put ??? next to.  If you answer them here and re-open this PR I'll updated it for you:

Is there a way to see when features were added before 0.6.6?

Can you confirm the units for xbarBP0, xbarBP1, xbarMax, ACLminSpeed, CruiseDelta, CruiseEnableMin, cameraOffset, leadDistance?

Can you explain what enabling epsModded does?

Can you explain if tuneGernby does anything else besides enabling the live tuning script?

**Comment by kegman** [comment]
Hi Steve, appreciate the effort in tidying up the readme.  

Before 0.6.6 my github got wiped so, no unfortunately.

i believe all the units are:

leadDistance is in m
cameraOffset in m
CruiseEnableMin in km/h
ALCminSpeed in m/s
CruiseDelta in km/h
leadDistance in m


epsModded is for modded cars (currently only civics) which uses a more suitable steerRatio, Kp, Kf, and Ki for modded steering.

tuneGerby is defunct - but should be left as default which is 1


Thanks again for your great efforts!

**Comment by steveham3** [comment]
A couple more questions:

Is liveParams defunct as well?  Doesn't your fork freeze the steerRatio?  Or does this this only happen if steerRatio is -1?

I'm still not sure what leadDistance is.  Someone on Discord said it was for Accords and Insights only and was the distance of when to resume from a stop

**Comment by steveham3** [comment]
Just following up with the previous questions so I can finalize the last changes

**Comment by kegman** [comment]
liveParams is defunct.  It still freezes steerRatio so that it doesn't change from the setting in kegman.json.  STOPPING_DISTANCE is for all cars.  LeadDistance is only for Bosch vehicles..

**Pull request merged**
